version: '3'
services:
  client:
    image: 'matthewjhcarr/multi-client'
    hostname: 'client'
    mem_limit: 128m
  nginx:
    image: 'matthewjhcarr/multi-nginx'
    hostname: 'nginx'
    mem_limit: 128m
    ports:
      - '80:80'
  server:
    image: 'matthewjhcarr/multi-server'
    hostname: 'api'
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'matthewjhcarr/multi-worker'
    hostname: 'worker'
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT